### ISSUE TITLE
compose.lock does not allow installation with PHP 7.1 or 7.2

### ISSUE THREAD

**Issue by llaville** [DamienHarper/doctrine-audit-bundle-demo#3]
Hello,
I've justed test your bundle and the demo, and i like it :) 

One issue with the demo. The `composer.lock` does not allow installation on PHP 7.1 or 7.2 platform.
Here is output when trying to do it with PHP 7.2

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/package-versions 1.5.1 -> satisfiable by ocramius/package-versions[1.5.1].
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.19) does not satisfy that requirement.
  Problem 2
    - ocramius/package-versions 1.5.1 requires php ^7.3.0 -> your PHP version (7.2.19) does not satisfy that requirement.
    - ocramius/proxy-manager 2.2.3 requires ocramius/package-versions ^1.1.3 -> satisfiable by ocramius/package-versions[1.5.1].
    - Installation request for ocramius/proxy-manager 2.2.3 -> satisfiable by ocramius/proxy-manager[2.2.3].
```

After deleting local copy of `composer.lock`, I'm able to install the demo, and all run fine !

Thanks for your works

**Comment by DamienHarper** [comment]
@llaville thanks for the report and glad you enjoy the bundle, I’ll have a look at this issue  ASAP.

**Comment by DamienHarper** [comment]
@llaville it is fixed on master `branch`

**Comment by llaville** [comment]
Hello Damien. 
It seems that the issue is back again since Symfony 5 support !

I've clone again the fresh master branch and try a `composer install` with PHP 7.3, and got 

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for ocramius/proxy-manager 2.5.0 -> satisfiable by ocramius/proxy-manager[2.5.0].
    - ocramius/proxy-manager 2.5.0 requires php ^7.4.0 -> your PHP version (7.3.14) does not satisfy that requirement.
  Problem 2
    - ocramius/proxy-manager 2.5.0 requires php ^7.4.0 -> your PHP version (7.3.14) does not satisfy that requirement.
    - doctrine/migrations 2.2.0 requires ocramius/proxy-manager ^2.0.2 -> satisfiable by ocramius/proxy-manager[2.5.0].
    - Installation request for doctrine/migrations 2.2.0 -> satisfiable by doctrine/migrations[2.2.0].
```

By removing the `composer.lock` i've been able to install demo again !
